nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Unknown error)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Unknown error)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Unknown error)
______________________________________
FlyOS Panel
启动中
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/etc/flyos/panel/server.py", line 47, in <module>
    start_server(main, debug=True, port=8888)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywebio/platform/tornado.py", line 217, in start_server
    _, port = _setup_server(webio_handler=handler, port=port, host=host, **tornado_app_settings)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywebio/platform/tornado.py", line 157, in _setup_server
    server = app.listen(port, address=host)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tornado/web.py", line 2109, in listen
    server.listen(port, address)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
______________________________________
FlyOS Panel
启动中
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/etc/flyos/panel/shell.py", line 41, in <module>
    start_server(main, debug=True, port=8887)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywebio/platform/tornado.py", line 217, in start_server
    _, port = _setup_server(webio_handler=handler, port=port, host=host, **tornado_app_settings)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywebio/platform/tornado.py", line 157, in _setup_server
    server = app.listen(port, address=host)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tornado/web.py", line 2109, in listen
    server.listen(port, address)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Unknown error)
___________________
FlyOS Virtual Machine
启动中
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/etc/flyos/virtualmachine/web.py", line 43, in <module>
    start_server(main, debug=True, port=8002)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywebio/platform/tornado.py", line 217, in start_server
    _, port = _setup_server(webio_handler=handler, port=port, host=host, **tornado_app_settings)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pywebio/platform/tornado.py", line 157, in _setup_server
    server = app.listen(port, address=host)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tornado/web.py", line 2109, in listen
    server.listen(port, address)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Unknown error)
nginx: [emerg] still could not bind()
